# smlsqlite - a binding of SQLite for Standard ML.
#
# Copyright (c) 2005, 2006 Henning Niss and Ken Friis Larsen.
# All rights reserved. See the file LICENSE for license information.

.PHONY: clean
clean:
	$(RM) *~ *.ui *.uo 
	$(RM) msqlite.{o,so}
